// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relation.proto

package edu.ucr.cs.qpe;

public final class RelationProtos {
  private RelationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RelationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .qpe.proto.Relation.OpCode op = 1;
    /**
     * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
     */
    boolean hasOp();
    /**
     * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
     */
    edu.ucr.cs.qpe.RelationProtos.Relation.OpCode getOp();

    // repeated .qpe.proto.Relation relations = 2;
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    java.util.List<edu.ucr.cs.qpe.RelationProtos.Relation> 
        getRelationsList();
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    edu.ucr.cs.qpe.RelationProtos.Relation getRelations(int index);
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    int getRelationsCount();
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    java.util.List<? extends edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder> 
        getRelationsOrBuilderList();
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder getRelationsOrBuilder(
        int index);

    // optional int64 rows = 3;
    /**
     * <code>optional int64 rows = 3;</code>
     */
    boolean hasRows();
    /**
     * <code>optional int64 rows = 3;</code>
     */
    long getRows();

    // optional int64 width = 4;
    /**
     * <code>optional int64 width = 4;</code>
     */
    boolean hasWidth();
    /**
     * <code>optional int64 width = 4;</code>
     */
    long getWidth();

    // optional int64 result = 5;
    /**
     * <code>optional int64 result = 5;</code>
     */
    boolean hasResult();
    /**
     * <code>optional int64 result = 5;</code>
     */
    long getResult();
  }
  /**
   * Protobuf type {@code qpe.proto.Relation}
   */
  public static final class Relation extends
      com.google.protobuf.GeneratedMessage
      implements RelationOrBuilder {
    // Use Relation.newBuilder() to construct.
    private Relation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Relation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Relation defaultInstance;
    public static Relation getDefaultInstance() {
      return defaultInstance;
    }

    public Relation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Relation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              edu.ucr.cs.qpe.RelationProtos.Relation.OpCode value = edu.ucr.cs.qpe.RelationProtos.Relation.OpCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                op_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                relations_ = new java.util.ArrayList<edu.ucr.cs.qpe.RelationProtos.Relation>();
                mutable_bitField0_ |= 0x00000002;
              }
              relations_.add(input.readMessage(edu.ucr.cs.qpe.RelationProtos.Relation.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              rows_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              width_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              result_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          relations_ = java.util.Collections.unmodifiableList(relations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.ucr.cs.qpe.RelationProtos.internal_static_qpe_proto_Relation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.ucr.cs.qpe.RelationProtos.internal_static_qpe_proto_Relation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.ucr.cs.qpe.RelationProtos.Relation.class, edu.ucr.cs.qpe.RelationProtos.Relation.Builder.class);
    }

    public static com.google.protobuf.Parser<Relation> PARSER =
        new com.google.protobuf.AbstractParser<Relation>() {
      public Relation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Relation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Relation> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code qpe.proto.Relation.OpCode}
     */
    public enum OpCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>JOIN = 0;</code>
       */
      JOIN(0, 0),
      /**
       * <code>MAPJOIN = 1;</code>
       */
      MAPJOIN(1, 1),
      /**
       * <code>EXTRACT = 2;</code>
       */
      EXTRACT(2, 2),
      /**
       * <code>FILTER = 3;</code>
       */
      FILTER(3, 3),
      /**
       * <code>NONE = 26;</code>
       *
       * <pre>
       *FORWARD = 4;
       *GROUPBY = 5;
       *LIMIT = 6;
       *SCRIPT = 7;
       *SELECT = 8;
       *TABLESCAN = 9;
       *FILESINK = 10;
       *REDUCESINK = 11;
       *UNION = 12;
       *UDTF = 13;
       *LATERALVIEWJOIN = 14;
       *LATERALVIEWFORWARD = 15;
       *HASHTABLESINK = 16;
       *HASHTABLEDUMMY = 17;
       *PTF = 18;
       *MUX = 19;
       *DEMUX = 20;
       *EVENT = 21;
       *ORCFILEMERGE = 22;
       *RCFILEMERGE = 23;
       *MERGEJOIN = 24;
       *SPARKPRUNINGSINK = 25;
       * </pre>
       */
      NONE(4, 26),
      ;

      /**
       * <code>JOIN = 0;</code>
       */
      public static final int JOIN_VALUE = 0;
      /**
       * <code>MAPJOIN = 1;</code>
       */
      public static final int MAPJOIN_VALUE = 1;
      /**
       * <code>EXTRACT = 2;</code>
       */
      public static final int EXTRACT_VALUE = 2;
      /**
       * <code>FILTER = 3;</code>
       */
      public static final int FILTER_VALUE = 3;
      /**
       * <code>NONE = 26;</code>
       *
       * <pre>
       *FORWARD = 4;
       *GROUPBY = 5;
       *LIMIT = 6;
       *SCRIPT = 7;
       *SELECT = 8;
       *TABLESCAN = 9;
       *FILESINK = 10;
       *REDUCESINK = 11;
       *UNION = 12;
       *UDTF = 13;
       *LATERALVIEWJOIN = 14;
       *LATERALVIEWFORWARD = 15;
       *HASHTABLESINK = 16;
       *HASHTABLEDUMMY = 17;
       *PTF = 18;
       *MUX = 19;
       *DEMUX = 20;
       *EVENT = 21;
       *ORCFILEMERGE = 22;
       *RCFILEMERGE = 23;
       *MERGEJOIN = 24;
       *SPARKPRUNINGSINK = 25;
       * </pre>
       */
      public static final int NONE_VALUE = 26;


      public final int getNumber() { return value; }

      public static OpCode valueOf(int value) {
        switch (value) {
          case 0: return JOIN;
          case 1: return MAPJOIN;
          case 2: return EXTRACT;
          case 3: return FILTER;
          case 26: return NONE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OpCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OpCode>() {
              public OpCode findValueByNumber(int number) {
                return OpCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.ucr.cs.qpe.RelationProtos.Relation.getDescriptor().getEnumTypes().get(0);
      }

      private static final OpCode[] VALUES = values();

      public static OpCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private OpCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:qpe.proto.Relation.OpCode)
    }

    private int bitField0_;
    // optional .qpe.proto.Relation.OpCode op = 1;
    public static final int OP_FIELD_NUMBER = 1;
    private edu.ucr.cs.qpe.RelationProtos.Relation.OpCode op_;
    /**
     * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
     */
    public edu.ucr.cs.qpe.RelationProtos.Relation.OpCode getOp() {
      return op_;
    }

    // repeated .qpe.proto.Relation relations = 2;
    public static final int RELATIONS_FIELD_NUMBER = 2;
    private java.util.List<edu.ucr.cs.qpe.RelationProtos.Relation> relations_;
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    public java.util.List<edu.ucr.cs.qpe.RelationProtos.Relation> getRelationsList() {
      return relations_;
    }
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    public java.util.List<? extends edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder> 
        getRelationsOrBuilderList() {
      return relations_;
    }
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    public int getRelationsCount() {
      return relations_.size();
    }
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    public edu.ucr.cs.qpe.RelationProtos.Relation getRelations(int index) {
      return relations_.get(index);
    }
    /**
     * <code>repeated .qpe.proto.Relation relations = 2;</code>
     *
     * <pre>
     *optional Relation relations = 2;
     * </pre>
     */
    public edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder getRelationsOrBuilder(
        int index) {
      return relations_.get(index);
    }

    // optional int64 rows = 3;
    public static final int ROWS_FIELD_NUMBER = 3;
    private long rows_;
    /**
     * <code>optional int64 rows = 3;</code>
     */
    public boolean hasRows() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 rows = 3;</code>
     */
    public long getRows() {
      return rows_;
    }

    // optional int64 width = 4;
    public static final int WIDTH_FIELD_NUMBER = 4;
    private long width_;
    /**
     * <code>optional int64 width = 4;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 width = 4;</code>
     */
    public long getWidth() {
      return width_;
    }

    // optional int64 result = 5;
    public static final int RESULT_FIELD_NUMBER = 5;
    private long result_;
    /**
     * <code>optional int64 result = 5;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 result = 5;</code>
     */
    public long getResult() {
      return result_;
    }

    private void initFields() {
      op_ = edu.ucr.cs.qpe.RelationProtos.Relation.OpCode.JOIN;
      relations_ = java.util.Collections.emptyList();
      rows_ = 0L;
      width_ = 0L;
      result_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, op_.getNumber());
      }
      for (int i = 0; i < relations_.size(); i++) {
        output.writeMessage(2, relations_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, rows_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, op_.getNumber());
      }
      for (int i = 0; i < relations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, relations_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rows_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, width_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.ucr.cs.qpe.RelationProtos.Relation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucr.cs.qpe.RelationProtos.Relation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code qpe.proto.Relation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.ucr.cs.qpe.RelationProtos.internal_static_qpe_proto_Relation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.ucr.cs.qpe.RelationProtos.internal_static_qpe_proto_Relation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.ucr.cs.qpe.RelationProtos.Relation.class, edu.ucr.cs.qpe.RelationProtos.Relation.Builder.class);
      }

      // Construct using edu.ucr.cs.qpe.RelationProtos.Relation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRelationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        op_ = edu.ucr.cs.qpe.RelationProtos.Relation.OpCode.JOIN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (relationsBuilder_ == null) {
          relations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          relationsBuilder_.clear();
        }
        rows_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        result_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.ucr.cs.qpe.RelationProtos.internal_static_qpe_proto_Relation_descriptor;
      }

      public edu.ucr.cs.qpe.RelationProtos.Relation getDefaultInstanceForType() {
        return edu.ucr.cs.qpe.RelationProtos.Relation.getDefaultInstance();
      }

      public edu.ucr.cs.qpe.RelationProtos.Relation build() {
        edu.ucr.cs.qpe.RelationProtos.Relation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.ucr.cs.qpe.RelationProtos.Relation buildPartial() {
        edu.ucr.cs.qpe.RelationProtos.Relation result = new edu.ucr.cs.qpe.RelationProtos.Relation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.op_ = op_;
        if (relationsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            relations_ = java.util.Collections.unmodifiableList(relations_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.relations_ = relations_;
        } else {
          result.relations_ = relationsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rows_ = rows_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.ucr.cs.qpe.RelationProtos.Relation) {
          return mergeFrom((edu.ucr.cs.qpe.RelationProtos.Relation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.ucr.cs.qpe.RelationProtos.Relation other) {
        if (other == edu.ucr.cs.qpe.RelationProtos.Relation.getDefaultInstance()) return this;
        if (other.hasOp()) {
          setOp(other.getOp());
        }
        if (relationsBuilder_ == null) {
          if (!other.relations_.isEmpty()) {
            if (relations_.isEmpty()) {
              relations_ = other.relations_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRelationsIsMutable();
              relations_.addAll(other.relations_);
            }
            onChanged();
          }
        } else {
          if (!other.relations_.isEmpty()) {
            if (relationsBuilder_.isEmpty()) {
              relationsBuilder_.dispose();
              relationsBuilder_ = null;
              relations_ = other.relations_;
              bitField0_ = (bitField0_ & ~0x00000002);
              relationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRelationsFieldBuilder() : null;
            } else {
              relationsBuilder_.addAllMessages(other.relations_);
            }
          }
        }
        if (other.hasRows()) {
          setRows(other.getRows());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.ucr.cs.qpe.RelationProtos.Relation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.ucr.cs.qpe.RelationProtos.Relation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .qpe.proto.Relation.OpCode op = 1;
      private edu.ucr.cs.qpe.RelationProtos.Relation.OpCode op_ = edu.ucr.cs.qpe.RelationProtos.Relation.OpCode.JOIN;
      /**
       * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
       */
      public boolean hasOp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
       */
      public edu.ucr.cs.qpe.RelationProtos.Relation.OpCode getOp() {
        return op_;
      }
      /**
       * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
       */
      public Builder setOp(edu.ucr.cs.qpe.RelationProtos.Relation.OpCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .qpe.proto.Relation.OpCode op = 1;</code>
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        op_ = edu.ucr.cs.qpe.RelationProtos.Relation.OpCode.JOIN;
        onChanged();
        return this;
      }

      // repeated .qpe.proto.Relation relations = 2;
      private java.util.List<edu.ucr.cs.qpe.RelationProtos.Relation> relations_ =
        java.util.Collections.emptyList();
      private void ensureRelationsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          relations_ = new java.util.ArrayList<edu.ucr.cs.qpe.RelationProtos.Relation>(relations_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.ucr.cs.qpe.RelationProtos.Relation, edu.ucr.cs.qpe.RelationProtos.Relation.Builder, edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder> relationsBuilder_;

      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public java.util.List<edu.ucr.cs.qpe.RelationProtos.Relation> getRelationsList() {
        if (relationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(relations_);
        } else {
          return relationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public int getRelationsCount() {
        if (relationsBuilder_ == null) {
          return relations_.size();
        } else {
          return relationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public edu.ucr.cs.qpe.RelationProtos.Relation getRelations(int index) {
        if (relationsBuilder_ == null) {
          return relations_.get(index);
        } else {
          return relationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder setRelations(
          int index, edu.ucr.cs.qpe.RelationProtos.Relation value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.set(index, value);
          onChanged();
        } else {
          relationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder setRelations(
          int index, edu.ucr.cs.qpe.RelationProtos.Relation.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.set(index, builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder addRelations(edu.ucr.cs.qpe.RelationProtos.Relation value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.add(value);
          onChanged();
        } else {
          relationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder addRelations(
          int index, edu.ucr.cs.qpe.RelationProtos.Relation value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.add(index, value);
          onChanged();
        } else {
          relationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder addRelations(
          edu.ucr.cs.qpe.RelationProtos.Relation.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.add(builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder addRelations(
          int index, edu.ucr.cs.qpe.RelationProtos.Relation.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.add(index, builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder addAllRelations(
          java.lang.Iterable<? extends edu.ucr.cs.qpe.RelationProtos.Relation> values) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          super.addAll(values, relations_);
          onChanged();
        } else {
          relationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder clearRelations() {
        if (relationsBuilder_ == null) {
          relations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          relationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public Builder removeRelations(int index) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.remove(index);
          onChanged();
        } else {
          relationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public edu.ucr.cs.qpe.RelationProtos.Relation.Builder getRelationsBuilder(
          int index) {
        return getRelationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder getRelationsOrBuilder(
          int index) {
        if (relationsBuilder_ == null) {
          return relations_.get(index);  } else {
          return relationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public java.util.List<? extends edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder> 
           getRelationsOrBuilderList() {
        if (relationsBuilder_ != null) {
          return relationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(relations_);
        }
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public edu.ucr.cs.qpe.RelationProtos.Relation.Builder addRelationsBuilder() {
        return getRelationsFieldBuilder().addBuilder(
            edu.ucr.cs.qpe.RelationProtos.Relation.getDefaultInstance());
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public edu.ucr.cs.qpe.RelationProtos.Relation.Builder addRelationsBuilder(
          int index) {
        return getRelationsFieldBuilder().addBuilder(
            index, edu.ucr.cs.qpe.RelationProtos.Relation.getDefaultInstance());
      }
      /**
       * <code>repeated .qpe.proto.Relation relations = 2;</code>
       *
       * <pre>
       *optional Relation relations = 2;
       * </pre>
       */
      public java.util.List<edu.ucr.cs.qpe.RelationProtos.Relation.Builder> 
           getRelationsBuilderList() {
        return getRelationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.ucr.cs.qpe.RelationProtos.Relation, edu.ucr.cs.qpe.RelationProtos.Relation.Builder, edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder> 
          getRelationsFieldBuilder() {
        if (relationsBuilder_ == null) {
          relationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.ucr.cs.qpe.RelationProtos.Relation, edu.ucr.cs.qpe.RelationProtos.Relation.Builder, edu.ucr.cs.qpe.RelationProtos.RelationOrBuilder>(
                  relations_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          relations_ = null;
        }
        return relationsBuilder_;
      }

      // optional int64 rows = 3;
      private long rows_ ;
      /**
       * <code>optional int64 rows = 3;</code>
       */
      public boolean hasRows() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 rows = 3;</code>
       */
      public long getRows() {
        return rows_;
      }
      /**
       * <code>optional int64 rows = 3;</code>
       */
      public Builder setRows(long value) {
        bitField0_ |= 0x00000004;
        rows_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 rows = 3;</code>
       */
      public Builder clearRows() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rows_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 width = 4;
      private long width_ ;
      /**
       * <code>optional int64 width = 4;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 width = 4;</code>
       */
      public long getWidth() {
        return width_;
      }
      /**
       * <code>optional int64 width = 4;</code>
       */
      public Builder setWidth(long value) {
        bitField0_ |= 0x00000008;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 width = 4;</code>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        width_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 result = 5;
      private long result_ ;
      /**
       * <code>optional int64 result = 5;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 result = 5;</code>
       */
      public long getResult() {
        return result_;
      }
      /**
       * <code>optional int64 result = 5;</code>
       */
      public Builder setResult(long value) {
        bitField0_ |= 0x00000010;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 result = 5;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000010);
        result_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qpe.proto.Relation)
    }

    static {
      defaultInstance = new Relation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:qpe.proto.Relation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qpe_proto_Relation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qpe_proto_Relation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016relation.proto\022\tqpe.proto\"\313\001\n\010Relation" +
      "\022&\n\002op\030\001 \001(\0162\032.qpe.proto.Relation.OpCode" +
      "\022&\n\trelations\030\002 \003(\0132\023.qpe.proto.Relation" +
      "\022\014\n\004rows\030\003 \001(\003\022\r\n\005width\030\004 \001(\003\022\016\n\006result\030" +
      "\005 \001(\003\"B\n\006OpCode\022\010\n\004JOIN\020\000\022\013\n\007MAPJOIN\020\001\022\013" +
      "\n\007EXTRACT\020\002\022\n\n\006FILTER\020\003\022\010\n\004NONE\020\032B \n\016edu" +
      ".ucr.cs.qpeB\016RelationProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qpe_proto_Relation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qpe_proto_Relation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qpe_proto_Relation_descriptor,
              new java.lang.String[] { "Op", "Relations", "Rows", "Width", "Result", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
